apiVersion: v1
kind: Pod
metadata:
  name: pod-volume
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      volumeMounts:
        - mountPath: /volume-host
          name: primeiro-volume
    - name: jenkins-container
      image: jenkins:2.60.3-alpine
      volumeMounts:
        - mountPath: /volume-host
          name: primeiro-volume
  volumes:
    - name: primeiro-volume
      hostPath: 
        path: /run/desktop/mnt/host/C/Renato/estudos-kubernetes/segundo-volume
        type: DirectoryOrCreate