apiVersion: v1
kind: Pod
metadata:
    name: pod-pv2
spec:
  containers:
    - name: nginx-container
      image: nginx-latest
      volumeMounts:
        - mountPath: /volume-dentro-do-container
          name: segundo-pv
  volumes:
    - name: segundo-pv
      persistentVolumeClaim:
        claimName: pvc-2