apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sistema-noticias-statefulset
spec:
  template:
    metadata:
      name: sistema-noticias
      labels:
        app: sistema-noticias
    spec:
      containers:
        - name: sistema-noticias-container
          image: aluracursos/sistema-noticias:1
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: sistema-noticias-configmap
          volumeMounts:
            - mountPath: /var/www/html/uploads
              name: imagens
            - mountPath: /tmp
              name: sessoes
          livenessProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 5
            failureThreshold: 3
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 10
            failureThreshold: 2
            initialDelaySeconds: 5
      volumes:
        - name: imagens
          persistentVolumeClaim:
            claimName: imagens-pvc
        - name: sessoes
          persistentVolumeClaim:
            claimName: sessoes-pvc
  replicas: 1
  selector:
    matchLabels:
      app: sistema-noticias
  serviceName: svc-sistema-noticias